# Generated by Django 3.0.7 on 2020-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20200626_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
